### ISSUE TITLE
bin directory not installed under prefix

### ISSUE THREAD

**Issue by psteinb** [NVlabs/nvbio-gpl#4]
Hi,
I pulled the master branch and received commit 3e6efbdf5f8e6ac69beaed2f78bb64ac5aab3e09
when I issue 

``` bash
$ make install
#...
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /home/steinbac/software/nvbio/0.x-3e6efbdf5/lib/libz.so.1.2.7
-- Up-to-date: /home/steinbac/software/nvbio/0.x-3e6efbdf5/lib/libz.so.1
-- Up-to-date: /home/steinbac/software/nvbio/0.x-3e6efbdf5/lib/libz.so
-- Up-to-date: /home/steinbac/software/nvbio/0.x-3e6efbdf5/lib/libz.a
-- Up-to-date: /home/steinbac/software/nvbio/0.x-3e6efbdf5/include/zconf.h
-- Up-to-date: /home/steinbac/software/nvbio/0.x-3e6efbdf5/include/zlib.h
-- Up-to-date: /home/steinbac/software/nvbio/0.x-3e6efbdf5/share/man/man3/zlib.3
-- Up-to-date: /home/steinbac/software/nvbio/0.x-3e6efbdf5/share/pkgconfig/zlib.pc
$
```

the entire binary dir is missing from the install tree AFAIK.
details:
centos 6.4
cuda 5.5.22
cmake 2.8.11

**Comment by nsubtil** [comment]
This is an artifact of how we use cmake internally. The binaries are copied to a 'bin' directory at the top of the source tree during the build step, which breaks the install target.

We'll get this fixed soon. Thanks for the bug report!

**Comment by nsubtil** [comment]
Fixed with 0f8c861d

**Comment by pescobar** [comment]
Hi

I have compiled release 0.9.7 and also the latest code available in master branch and I always get this problem. After running "make install" I only get the folders "include", "lib" and "share" in the installation directory, not the "bin" folder

I have verified that the binaries "nvBowtie", "nvSSA", "nvExtractReads"...etc are compiled (each of them is in their own folder after running make) but they are just not copied to the installation directory when doing the "make install"

I am using CMake-2.8.11, GCC-4.8.2, make-3.81 and Cuda-5.5.22 in Centos6.5 x86_64

**Comment by mboisson** [comment]
Same here, make install does not work. The only thing it installs is "libz" (which it should not even build as it is installed on our system).

**Comment by nsubtil** [comment]
Sounds like this still needs work. Reopening.

**Comment by pescobar** [comment]
just to update this issue, I tried to install latest release 0.9.9.3 and this problem still exists
